name: PR Notification
on:
  pull_request:
    types: [opened, reopened]

jobs:
  pr_alert:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack of PR
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "ğŸ”Œ *New Pull Request Opened!* \n\n*ğŸ“Œ Feature:* ${{ github.event.pull_request.title }}\n*ğŸ‘¤ Author:* ${{ github.actor }}\n*ğŸŒ¿ Branches:* `${{ github.head_ref }}` â¡ï¸ `${{ github.base_ref }}`\n\n*ğŸ“ Description:*\n${{ github.event.pull_request.body }}\n\n----------------------------------\nğŸ‘€ <${{ github.event.pull_request.html_url }}|Review this PR on GitHub>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          
