name: Notify Slack
on: [push]

jobs:
  slack-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # We use a standard JSON payload that includes a fallback "text" field
          # This prevents the "no_text" error you saw.
          payload: |
            {
              "text": "ğŸš€ *New Update Published!* \n\n*ğŸ“ Project:* ${{ github.repository }}\n*ğŸ‘¤ Developer:* ${{ github.actor }}\n*ğŸ“ Message:* ${{ github.event.head_commit.message }}\n\n<https://github.com/${{ github.repository }}/commit/${{ github.sha }}|ğŸ‘‰ Click here to View Changes>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          
